name: Basic github workflow
on: 
  push:
    branches-ignore : ["master"]

  pull-request: 
    types: [opened, reopened]

  workflow_dispatch:
    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Detect package manager
